---
  - name: Install nginx
    become: yes
    apt: name=nginx state=latest

  - name: Starting nginx
    become: yes
    service: name=nginx state=started enabled=true

  - name: Delete default nginx conf file
    become: yes
    file: path=/etc/nginx/sites-enabled/default state=absent
    notify: reload nginx

  - name: Install php7.0
    become: yes
    include: php.yml

  - name: Websites config
    include: site.yml
    with_items: domains
