---
  - name: Adding DotDeb repository
    apt_repository: repo='{{ item }}'
    with_items:
      - deb http://packages.dotdeb.org jessie all
      - deb-src http://packages-dotdeb.org jessie all

  - name: Adding DotDeb key
    apt_key: url=https://www.dotdeb.org/dotdeb.gpg

  - name: update apt
    apt: update_cache=yes

  - name: Installing php
    apt: name={{ item }} state=latest
    with_items:
      - php7.0
      - php7.0-common
      - php7.0-cli
      - php7.0-intl
      - php7.0-curl
      - php7.0-cgi
      - php7.0-fpm
      - php7.0-mcrypt
      - php7.0-mysql
      - php7.0-gd