---
  - name: "Creating directory /home/{{ client.username }}/{{ client.domain }}"
    become: yes
    file: path=/home/{{ client.username }}/{{ client.domain }} state=directory owner={{ client.username }}

  - name: Link to www
    become: yes
    file: src=/home/{{ client.username }}/{{ client.domain }} dest=/var/www/{{ client.domain }} state=link

  - name: Configuring nginx
    become: yes
    template: src=templates/nginx.j2 dest=/etc/nginx/sites-available/{{ client.domain }} force=yes
    notify: reload nginx

  - name: Activating {{ client.domain }}
    become: yes
    file: src=/etc/nginx/sites-available/{{ client.domain  }} dest=/etc/nginx/sites-enabled/{{ client.domain }} state=link
    notify: reload nginx
