---
  - name: "Creating directory /home/{{ client.username }}/www"
    become: yes
    file: path=/home/{{ client.username }}/www state=directory owner={{ client.username }}

  - name: Link to www
    become: yes
    file: src=/home/{{ client.username }}/www dest=/var/www/{{ client.username }} state=link

  - name: Configuring nginx
    become: yes
    template: src=templates/nginx.j2 dest=/etc/nginx/sites-available/{{ client.username }} force=yes
    notify: reload nginx

  - name: Activating {{ client.domain }}
    become: yes
    file: src=/etc/nginx/sites-available/{{ client.username }} dest=/etc/nginx/sites-enabled/{{ client.username }} state=link
    notify: reload nginx
