---
  - name: "Creating directory /home/{{ user }}/{{ item }}"
    become: yes
    file: path=/home/{{ user }}/{{ item }} state=directory owner={{ user }}

  - name: Link to www
    become: yes
    file: src=/home/{{ user }}/{{ item }} dest=/var/www/{{ item }} state=link

  - name: Configuring nginx
    become: yes
    template: src=templates/nginx.j2 dest=/etc/nginx/sites-available/{{ item }} force=yes
    notify: reload nginx

  - name: Activating {{ item }}
    become: yes
    file: src=/etc/nginx/sites-available/{{ item  }} dest=/etc/nginx/sites-enabled/{{ item }} state=link
    notify: reload nginx