---
- name: VPS OVH Install
  hosts: vpsovh
  remote_user: groot
  vars:
    user: groot
    domains:
      - sghir.me
    php_packages:
      - php7.0
      - php7.0-common
      - php7.0-cli
      - php7.0-intl
      - php7.0-curl
      - php7.0-cgi
      - php7.0-fpm
      - php7.0-mcrypt
      - php7.0-mysql
      - php7.0-gd

  roles:
  #  - utils
  #  - user
    - nginx
...
