---
- name: VPS OVH Install
  hosts: vpsovh
  remote_user: root
  vars:
    client:
      username: rivalia
      password: houdhoudarivalia
      domain: rivalia.sghir.me

  roles:
    #- utils
    #- user
    #- nginx
    #- {role: mysql, mysql_root_db_pass: VnCdE28u, mysql_db: none, mysql_repl_user: none }
...
