---
  - name: Creating {{ client.username }} user with {{ client.password }} password
    when: client.username is defined
    user: name={{ client.username }} password={{ client.password | password_hash("sha512") }}

  - name: Adding ssh key to {{ client.username }}
    when: client.username is defined
    authorized_key: user={{ client.username }} key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

#  - name: make {{ user }} sudoer
#    when: user is defined
#    template: src=templates/sudoers.j2 dest=/etc/sudoers.d/{{ user }}-sudoer validate='visudo -cf %s'
