---
  - name: Installing tools
    apt: name={{ item }} update_cache=yes state=latest
    with_items:
      - ufw
      - vim
      - htop
      - zsh
      - git

  - name: allow OpenSSH on ufw
    ufw:
      rule: allow
      name: OpenSSH

  - name: enable ufw
    ufw:
      state: enabled
